console.log(Math.sqrt(25)); //55
//potencia
console.log(Math.pow(3,2)); 
console.log(Math.pow(4,3));

//Arredondamento
console.log (Math.round (4,4)); //4
console.log (Math.round (4,7)); //5

//arredonda para o valor mais alto (ceil)
console.log (Math.ceil (4,1)); //5
//Arrendoda para o valor mais baixo (floor)
console.log (Math.floor (4,9)); //4


//Aleatorio

console.log (Math.random()); // 0 => 1

//0 => 100
console.log (Math.random(Math.random()*100 )); 

//1 => 100
console.log(Math.ceil(Math.random()*100));

//0 => 99
console.log(Math.floor(Math.random()*100));


//Desafio 

//0 => 50
console.log(Math.round(Math.random()*50));
//50 => 100
console.log(Math.round(Math.random()*50+50));
//30 =>40 (10)
console.log(Math.round(Math.random()*10+30));

//Max, Min, Abosolute(Abs)
console.loh(matchMedia.max(1,3,6,9,2,5)); //9
console.loh(matchMedia.max(1,3,6,9,2,5)); //1
console.log(Math(-10));  //10
